import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import { ComponentProps } from "react";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<Nav />
				{children}
			</body>
		</html>
	);
}

const Nav = () => {
	//
	return (
		<div className='group'>
			<nav className='flex p-2 relative justify-between items-center'>
				<Title />
				<div className='flex gap-3 items-center'>
					<NavLink href={"/"}>Obituary</NavLink>
					<NavLink href={"/"}>Gallery</NavLink>
					<NavLink href={"/"}>Funeral</NavLink>
				</div>
				<DonateButton />
			</nav>
			<hr className='w-[90%] mx-auto my-0 group-hover:scale-x-110 group-hover:border-foreground transition-all' />
		</div>
	);
};

const NavLink = ({ className, ...props }: ComponentProps<typeof Link>) => {
	//
	return (
		<div className='flex justify-center items-center p-2 h-full text-muted-foreground rounded-lg text-xs hover:bg-muted transition-colors hover:cursor-pointer hover:text-foreground underline-offset-2 hover:underline'>
			<Link
				className={cn("", className)}
				{...props}
			/>
		</div>
	);
};

const Title = () => {
	//
	return (
		<div className='flex flex-col gap-[.0625rem] justify-center items-start'>
			<span className={`text-muted-foreground text-sm font-['cursive']`}>
				In loving memory of
			</span>
			<h1 className='text-lg font-semibold'>Tyler Zander</h1>
		</div>
	);
};

const DonateButton = () => {
	//
	return (
		<a
			href='https://gofund.me/65a94ed6'
			target='_blank'
			className=''
		>
			<Button>Donate💕</Button>
		</a>
	);
};
